[package]
name = "aoc2019"
version = "0.1.0"
authors = ["Patrick Himmelmann <patrick.himmelmann@kit.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ureq = "2.2"
num-complex = "0.4"
itertools = "0.10"